# Generated by Django 3.2.5 on 2021-09-17 15:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('employee', models.IntegerField()),
                ('day', models.DateField()),
                ('slice', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BalanceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('employee', models.IntegerField()),
                ('day', models.DateField()),
                ('slice', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('employeeId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FireSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('day', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FireStampCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('day', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('employee', models.IntegerField()),
                ('stampGroup', models.CharField(max_length=3)),
                ('day', models.DateField()),
                ('entry', models.DateField()),
                ('exit', models.DateField()),
                ('entryMin', models.IntegerField()),
                ('exitMin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StampCheckError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('employee', models.IntegerField()),
                ('day', models.DateField()),
                ('stampType', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('errorMessage', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Timekeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('employee', models.IntegerField()),
                ('day', models.DateField()),
                ('type', models.CharField(max_length=3)),
                ('code', models.CharField(max_length=3)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stampGroup', models.CharField(choices=[('G01', 'Stamp group No 01'), ('G02', 'Stamp group No 02'), ('G03', 'Stamp group No 03'), ('G04', 'Stamp group No 04'), ('G05', 'Stamp group No 05'), ('G06', 'Stamp group No 06'), ('G07', 'Stamp group No 07'), ('G08', 'Stamp group No 08'), ('G09', 'Stamp group No 09'), ('G10', 'Stamp group No 10')], default='G01', max_length=3)),
                ('stampType', models.CharField(choices=[('IN', 'Entry stamp'), ('OU', 'Exit stamp')], default='IN', max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_stamps', to='shifts.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stamps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=64)),
                ('stampGroup', models.CharField(choices=[('G01', 'Stamp group No 01'), ('G02', 'Stamp group No 02'), ('G03', 'Stamp group No 03'), ('G04', 'Stamp group No 04'), ('G05', 'Stamp group No 05'), ('G06', 'Stamp group No 06'), ('G07', 'Stamp group No 07'), ('G08', 'Stamp group No 08'), ('G09', 'Stamp group No 09'), ('G10', 'Stamp group No 10')], default='G01', max_length=3)),
                ('start', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4320)])),
                ('end', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4320)])),
                ('requiredTime', models.IntegerField()),
                ('presenceCode', models.CharField(max_length=3)),
                ('absenceCode', models.CharField(max_length=3)),
                ('overtimeCode', models.CharField(max_length=3)),
                ('overtimeMin', models.IntegerField()),
                ('overtimeStep', models.IntegerField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='shifts.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_slices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedules', to='shifts.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to='shifts.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='schedules',
            field=models.ManyToManyField(related_name='employees_asigned', through='shifts.Schedule', to='shifts.Shift'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='slice',
            constraint=models.CheckConstraint(check=models.Q(('start__gte', 0), ('start__lte', 4320)), name='start_range'),
        ),
        migrations.AddConstraint(
            model_name='slice',
            constraint=models.CheckConstraint(check=models.Q(('end__gte', 0), ('end__lte', 4320)), name='end_range'),
        ),
        migrations.AddConstraint(
            model_name='slice',
            constraint=models.CheckConstraint(check=models.Q(('start__lte', django.db.models.expressions.F('end'))), name='start_end_lessthan'),
        ),
        migrations.AddConstraint(
            model_name='slice',
            constraint=models.CheckConstraint(check=models.Q(('requiredTime__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('end'), '-', django.db.models.expressions.F('start')))), name='requiredTime_lessthan'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='uniquelabel'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('user', 'employee', 'day'), name='uniqueScheduleDay'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('user', 'employeeId'), name='uniqueConsEmployeeId'),
        ),
    ]
