# Generated by Django 3.2.5 on 2021-09-17 15:48

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='uniqueConsEmployeeId',
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='uniqueScheduleDay',
        ),
        migrations.RemoveConstraint(
            model_name='shift',
            name='uniquelabel',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('user', 'employeeId'), name='uniqueEmployeeId'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('user', 'employee', 'day'), name='uniqueDay'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='uniqueShiftlabel'),
        ),
    ]
