# Generated by Django 3.2.5 on 2021-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_auto_20210917_1248'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='uniqueEmployeeId',
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('user', 'employeeId'), name='uniqueEmployeeId'),
        ),
    ]
