# Generated by Django 3.2.5 on 2021-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_auto_20210917_1252'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stamp',
            constraint=models.CheckConstraint(check=models.Q(('stampType', 'IN'), ('stampType', 'OU'), _connector='OR'), name='stampType_MustBe_IN_or_OU'),
        ),
    ]
