# Generated by Django 3.2.5 on 2021-09-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_stamp_stamptype_mustbe_in_or_ou'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stamp',
            constraint=models.UniqueConstraint(fields=('user', 'employee', 'timestamp'), name='duplicateTimestamp'),
        ),
    ]
